sudo: required

services:
  - docker

before_install:
  - docker build --tag dev --file test/Dockerfile .
  - docker run --name dev -d -i -v $PWD:$PWD -w $PWD dev sh

script:
  - docker exec dev make --version
  - docker exec dev make test
